name: Build macOS Installer

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build-pkg:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up package root structure
        run: |
          mkdir -p package-root/Library/LaunchAgents package-root/usr/local/bin package-root/usr/local/var/log
          cp com.marsegm.dailyupdate.plist package-root/Library/LaunchAgents/
          cp update.sh package-root/usr/local/bin/
          chmod +x package-root/usr/local/bin/update.sh
          touch package-root/usr/local/var/log/update.log package-root/usr/local/var/log/update.err

      - name: Build .pkg installer
        run: |
          pkgbuild --root package-root \
            --identifier com.marsegm.dailyupdate \
            --version 1.0.0 \
            --install-location / \
            macos-update.pkg

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-update-pkg
          path: macos-update.pkg 